

name: Flutter CI

on:
  push:
    branches:
      - main
      - feat/**
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.x'

    - name: Install dependencies
      run: flutter pub get

    - name: Run analyzer
      run: flutter analyze .

    - name: Format check
      run: flutter format --set-exit-if-changed lib/

    - name: Run tests
      run: flutter test --coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

